CREATE TABLE vouchers (
  id SERIAL PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  amount NUMERIC(18, 2) NOT NULL,
  created_by INTEGER NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  used_by INTEGER DEFAULT NULL,
  used_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
